// Generated by CoffeeScript 1.10.0
(function() {
  var Schema, Url, mongoose;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  Url = new Schema({
    num: Number,
    url: String
  });

  module.exports = mongoose.model("Url", Url);

}).call(this);
